UpSchool.HelpDesk.PresentationLayer/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using UpSchool.HelpDesk.PresentationLayer.ApiServices;
using UpSchool.HelpDesk.PresentationLayer.Models;

namespace UpSchool.HelpDesk.PresentationLayer.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly UserApiService userApiService;

        public ProfileController(UserApiService userApiService)
        {
            this.userApiService = userApiService;
        }

        public async Task<IActionResult> Index()
        {
            var stringId = User.Claims.SingleOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

            var id = int.Parse(stringId);
            var profileData = await this.userApiService.GetProfileAsync(id);
            return View(profileData.Data);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProfile(UpdateProfileModel model)
        {
            
            if(model.File != null)
            {
                var path = Directory.GetCurrentDirectory();
                var extension = Path.GetExtension(model.File.FileName);
                var newFileName = Guid.NewGuid()+extension;
                var savePath = Path.Combine(path, "wwwroot","images", newFileName);

                var stream = new FileStream(savePath, FileMode.Create);

                await model.File.CopyToAsync(stream);

                model.Image = newFileName;
            }

            await this.userApiService.UpdateProfile(new UpdateToProfileModel
            {
                Id = model.Id,
                Image = model.Image,
                Name = model.Name
            });

            return RedirectToAction("Index");
        }
    }
}

UpSchool.HelpDesk.PresentationLayer/Controllers/RapidApiController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using UpSchool.HelpDesk.PresentationLayer.Models;

namespace UpSchool.HelpDesk.PresentationLayer.Controllers
{
    public class RapidApiController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> List(string country)
        {
            var client = new HttpClient();

            var model = new RapidApiResultModel();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri($"https://covid-193.p.rapidapi.com/statistics?country={country}"),
                Headers =
    {
        { "X-RapidAPI-Key", "1df7bb17f3msh5618e48a55c4688p1b8dfajsn0e0862e6451f" },
        { "X-RapidAPI-Host", "covid-193.p.rapidapi.com" },
    },
            };
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var body = await response.Content.ReadAsStringAsync();
               model =  JsonConvert.DeserializeObject<RapidApiResultModel>(body);
            }
            return View(model);
        }
    }
}

UpSchool.HelpDesk.PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/assets/img/favicon.png">
    <title>
        UpSchool HelpDesk App
    </title>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
    <!-- Nucleo Icons -->
    <link href="~/assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- CSS Files -->
    <link id="pagestyle" href="~/assets/css/argon-dashboard.css?v=2.0.4" rel="stylesheet" />
</head>

<body class="g-sidenav-show   bg-gray-100">
    <div class="min-height-300 bg-primary position-absolute w-100"></div>
    <aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
        <div class="sidenav-header">
            <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
            <a class="navbar-brand m-0" href="#">
                <img src="~/assets/img/logo-ct-dark.png" class="navbar-brand-img h-100" alt="main_logo">
                <span class="ms-1 font-weight-bold">UpSchool HelpDesk App</span>
            </a>
        </div>
        <hr class="horizontal dark mt-0">
        <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
            <ul class="navbar-nav">


                @{


                    if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link " asp-action="Index" asp-controller="Profile">
                                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                    <i class="ni ni-single-02 text-dark text-sm opacity-10"></i>
                                </div>
                                <span class="nav-link-text ms-1">Profil Bilgilerim</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Dashboard">
                                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                    <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
                                </div>
                                <span class="nav-link-text ms-1">Dashboard</span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " asp-action="List" asp-controller="WorkRequest">
                                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                    <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
                                </div>
                                <span class="nav-link-text ms-1">Talepler</span>
                            </a>
                        </li>

                    }


                    if (User.IsInRole("Member"))
                    {
                        <li class="nav-item">
                            <a class="nav-link " asp-action="Index" asp-controller="Profile">
                                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                    <i class="ni ni-single-02 text-dark text-sm opacity-10"></i>
                                </div>
                                <span class="nav-link-text ms-1">Profil Bilgilerim</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-action="AssignToMe" asp-controller="WorkRequest">
                                <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                                    <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
                                </div>
                                <span class="nav-link-text ms-1">Atanan İşler</span>
                            </a>
                        </li>
                    }

                }



                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="RapidApi">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-credit-card text-success text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Rapid Api (COVID 19)</span>
                    </a>
                </li>


                <li class="nav-item">
                    <a class="nav-link " asp-action="Logout" asp-controller="Account">
                        <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                            <i class="ni ni-single-copy-04 text-warning text-sm opacity-10"></i>
                        </div>
                        <span class="nav-link-text ms-1">Çıkış Yap</span>
                    </a>
                </li>

            </ul>
        </div>

    </aside>
    <main class="main-content position-relative border-radius-lg ">
        <!-- Navbar -->
        <!-- End Navbar -->
        <div class="container-fluid py-4">
            @RenderBody()
            <footer class="footer pt-3  ">
                <div class="container-fluid">
                    <div class="row align-items-center justify-content-lg-between">
                        <div class="col-lg-6 mb-lg-0 mb-4">
                            <div class="copyright text-center text-sm text-muted text-lg-start">
                                © <script>
                                      document.write(new Date().getFullYear())
                                </script>,
                                made with Tuğba Karacak
                            </div>
                        </div>
                        <div class="col-lg-6">
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </main>

    <!--   Core JS Files   -->
    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/core/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script src="~/assets/js/plugins/chartjs.min.js"></script>

    @RenderSection("script",false)
  
    <script>
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="~/assets/js/argon-dashboard.min.js?v=2.0.4"></script>
</body>

@RenderBody()

</html>