UpSchool.HelpDesk.PresentationLayer/Controllers/WorkRequestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using UpSchool.HelpDesk.PresentationLayer.ApiServices;
using UpSchool.HelpDesk.PresentationLayer.Models;

namespace UpSchool.HelpDesk.PresentationLayer.Controllers
{
    [Authorize(Roles = "Admin,Member")]
    public class WorkRequestController : Controller
    {
        private readonly WorkRequestApiService workRequestApiService;
        private readonly UserApiService userApiService;

        public WorkRequestController(WorkRequestApiService workRequestApiService, UserApiService userApiService)
        {
            this.workRequestApiService = workRequestApiService;
            this.userApiService = userApiService;
        }

        public async Task<IActionResult> List()
        {
            var result = await this.workRequestApiService.GetAllAsync();
            return View(result.Data);
        }

        public IActionResult Create()
        {
            return View(new CreateWorkRequestModel());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateWorkRequestModel model)
        {
            if(ModelState.IsValid)
            {
                var result = await this.workRequestApiService.CreateAsync(model);
                if (result.IsSuccess)
                {
                    return RedirectToAction("List");
                }
                ModelState.AddModelError("","Sunucu tarafında bir hata oluştu, ürün yöneticinizle görüşünüz");
            }
         
            return View(model);
        }

   
        public async Task<IActionResult> Update(int id)
        {
            var result = await this.workRequestApiService.GetAsync(id);
            if (!result.IsSuccess) {
                ModelState.AddModelError("", "Sunucu tarafında bir hata oluştu, ürün yöneticinizle görüşünüz");
                return View(new WorkRequestModel());
            }
            return View(new UpdateWorkRequestModel
            {
                Id = result.Data.Id,
                Description= result.Data.Description,
                Title= result.Data.Title,
            });
        }


        [HttpPost]
        public async Task<IActionResult> Update(UpdateWorkRequestModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await this.workRequestApiService.UpdateAsync(model);
                if (!result.IsSuccess)
                {
                    ModelState.AddModelError("", "Sunucu tarafında bir hata oluştu, ürün yöneticinizle görüşünüz");
                    return View(new WorkRequestModel());
                }
                return RedirectToAction("List");
            }
            return View(model);
        }

        public async Task<IActionResult> AssignDeveloper(int workRequestId)
        {
            //bütün memberlar listenecek;

            var memberResult = await this.userApiService.GetMembersAsync();
            ViewBag.Members = memberResult.Data;
            return View(new AssignUserModel
            {
                WorkRequestId = workRequestId,
            });
        }

        [HttpPost]
        public async Task<IActionResult> AssignDeveloper(AssignUserModel model)
        {
            await this.workRequestApiService.AssignUserAsync(model);
            return RedirectToAction("List");
        }

        public async Task<IActionResult> AssignToMe()
        {
            var stringId = User.Claims.SingleOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;

            var id = int.Parse(stringId);
            var workRequestData = await this.workRequestApiService.GetWorkRequestsByUserIdAsync(id);

        

            return View(workRequestData.Data);
        }

        public async Task<IActionResult> SetCompleted(int id)
        {
            await this.workRequestApiService.CompletedAsync(id);
            return RedirectToAction("AssignToMe");
        }
    }
}

UpSchool.HelpDesk.PresentationLayer/Views/WorkRequest/AssignDeveloper.cshtml
@model AssignUserModel

@{
    Layout = "_Layout";
    List<ApplicationUserModel> memberList = (List<ApplicationUserModel>)ViewBag.Members;
}
@foreach (var member in memberList)
{
    <div class="card mb-3">
        <div class="card card-profile card-plain p-5">
            <div class="row">
                <div class="col-lg-5">
                    <a href="javascript:;">
                        <div class="position-relative">
                            <div class="blur-shadow-image">
                                <img class="w-75 rounded-3 shadow-lg" style="height:200px!important;" src="~/images/@member.Image">
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-7 ps-0 my-auto">
                    <div class="card-body text-left">
                        <div class="p-md-0 pt-3">
                            <h5 class="font-weight-bolder mb-0">@member.Name</h5>
                            <p class="text-uppercase text-sm font-weight-bold mb-2">@member.Email</p>
                        </div>
                     
                        <form asp-action="AssignDeveloper" asp-controller="WorkRequest">
                            <input type="hidden" asp-for="@Model.WorkRequestId" />
                            <input type="hidden" name="UserId" asp-for="UserId" value="@member.Id" />
                                <button type="submit" class="btn bg-gradient-info btn-lg w-100">Personeli Görevlendir</button>
                        </form>
                    
                    </div>
                </div>
            </div>
        </div>

    </div>

}

UpSchool.HelpDesk.PresentationLayer/Views/WorkRequest/AssignToMe.cshtml
@model List<WorkRequestModel>

@{
    Layout = "_Layout";
}

<div class="row">
    <div class="col-12">


        @if (Model?.Count > 0)
        {
            <div class="card mb-4">
                <div class="card-header pb-0">
                    <h6>Atanmış Talepler</h6>
                   
                </div>
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center justify-content-center mb-0">
                            <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Talep Başlığı</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Talep Açıklaması</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Durumu</th>
                                    <th></th>

                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <span class="ps-3 text-xs text-center font-weight-bold ">@item.Title</span>
                                        </td>
                                        <td>
                                            <span class="ps-1 text-xs text-center font-weight-bold">@item.Description</span>
                                        </td>
                                        <td>
                                            <span class="ps-1 text-xs text-center font-weight-bold">@item.State</span>
                                        </td>

                                        <td>
                                            <span class="ps-1 text-xs text-center font-weight-bold">

                                                <a asp-action="Index" asp-controller="WorkRequestState" asp-route-workRequestId="@item.Id" class="btn btn-primary btn-sm">Detay Gir</a>
                                             

                                            </span>
                                        </td>
                                        <td class="ps-1 text-xs text-center font-weight-bold">



                                            <a asp-action="SetCompleted" asp-controller="WorkRequest" asp-route-id="@item.Id" class="btn btn-info btn-sm"> Tamamla </a>
                                         




                                        </td>


                                    </tr>
                                }


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="card">
                <!-- Card image -->
                <div class="card-header p-0 mx-3 mt-3 position-relative z-index-1">
                </div>
                <!-- Card body -->
                <div class="card-body">
                    <h3 class="card-title mb-3">Uyarı</h3>
                    <p class="card-text mb-4">Üzerinizde herhangi bir atanmış iş bulunmamaktadır</p>
                  
                </div>
            </div>
        }





    </div>
</div>

UpSchool.HelpDesk.PresentationLayer/Views/WorkRequest/Create.cshtml
@model CreateWorkRequestModel

@{
    Layout = "_Layout";
}

<div class="card">
    <div class="card-body">
        <h3 class="card-title mb-3">Yeni Talep Oluştur</h3>
        <form asp-action="Create" asp-controller="WorkRequest">

            <div class="form-group">
                <label for="example-text-input" class="form-control-label">Başlık</label>
                <input class="form-control" type="text" asp-for="Title">
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Açıklama</label>
                <textarea class="form-control" asp-for="Description" rows="3"></textarea>
            </div>
            <div class="form-group text-danger" asp-validation-summary="All" >


            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg w-100">Kaydet</button>
            </div>
        </form>

    </div>

</div>

UpSchool.HelpDesk.PresentationLayer/Views/WorkRequest/List.cshtml
@model List<WorkRequestModel>

@{
    Layout = "_Layout";
}

<div class="row">
    <div class="col-12">


        @if (Model?.Count > 0)
        {
            <div class="card mb-4">
                <div class="card-header pb-0">
                    <h6>Talepler</h6>
                    <a asp-action="Create" asp-controller="WorkRequest" class="btn btn-primary btn-sm">Yeni Talep Oluştur</a>
                </div>
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center justify-content-center mb-0">
                            <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Talep Başlığı</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Talep Açıklaması</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Durumu</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder  opacity-7 ps-2">Atananan Developer</th>

                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <span class="ps-3 text-xs text-center font-weight-bold ">@item.Title</span>
                                        </td>
                                        <td>
                                            <span class="ps-1 text-xs text-center font-weight-bold">@item.Description</span>
                                        </td>
                                        <td>
                                            <span class="ps-1 text-xs text-center font-weight-bold">@item.State</span>
                                        </td>

                                        <td>
                                            <span class="ps-1 text-xs text-center font-weight-bold">

                                                @if (item.AssignedUserId == null)
                                                {
                                                    <a asp-action="AssignDeveloper" asp-controller="WorkRequest" asp-route-workRequestId ="@item.Id" class="btn btn-primary btn-sm">Ata</a>
                                                }
                                                else
                                                {
                                                    <getusername user-id="@item.AssignedUserId.Value"></getusername>

                                                }

                                            </span>
                                        </td>
                                        <td class="ps-1 text-xs text-center font-weight-bold">


                                            @if (item.AssignedUserId == null)
                                            {
                                                <a asp-action="Update" asp-controller="WorkRequest" asp-route-id="@item.Id" class="btn btn-info btn-sm"> Düzenle</a>
                                            }
                                            else
                                            {
                                                <span class="badge bg-gradient-danger">Düzenleme yapılamaz</span>
                                            }




                                        </td>


                                    </tr>
                                }


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="card">
                <!-- Card image -->
                <div class="card-header p-0 mx-3 mt-3 position-relative z-index-1">
                </div>
                <!-- Card body -->
                <div class="card-body">
                    <h3 class="card-title mb-3">Uyarı</h3>
                    <p class="card-text mb-4">Herhangi bir veri bulunamadı.</p>
                    <a asp-action="Create" asp-controller="WorkRequest" class="btn btn-primary">Yeni Talep Ekle</a>
                </div>
            </div>
        }





    </div>
</div>

UpSchool.HelpDesk.PresentationLayer/Views/WorkRequest/Update.cshtml
@model UpdateWorkRequestModel

@{
    Layout = "_Layout";
}

<div class="card">
    <div class="card-body">
        <h3 class="card-title mb-3">Talep Düzenle</h3>
        <form asp-action="Update" asp-controller="WorkRequest">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label for="example-text-input" class="form-control-label">Başlık</label>
                <input class="form-control" type="text" asp-for="Title">
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Açıklama</label>
                <textarea class="form-control" asp-for="Description" rows="3"></textarea>
            </div>
            <div class="form-group text-danger" asp-validation-summary="All" >


            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg w-100">Kaydet</button>
            </div>
        </form>

    </div>

</div>