UpSchool.HelpDesk.PresentationLayer/Controllers/WorkRequestStateController.cs
using FastMember;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using System.Data;
using System.Drawing.Printing;
using System.Reflection;
using System.Reflection.Metadata;
using UpSchool.HelpDesk.PresentationLayer.ApiServices;
using UpSchool.HelpDesk.PresentationLayer.Models;

namespace UpSchool.HelpDesk.PresentationLayer.Controllers
{
    public class WorkRequestStateController : Controller
    {
        private readonly WorkRequestStateApiService workRequestStateApiService;

        public WorkRequestStateController(WorkRequestStateApiService workRequestStateApiService)
        {
            this.workRequestStateApiService = workRequestStateApiService;

        }
        public async Task<IActionResult> Index(int workRequestId)
        {
            var result = await this.workRequestStateApiService.GetWorkRequestStatesAsync(workRequestId);

            ViewBag.WorkRequestId = workRequestId;
            return View(result.Data);
        }

        public async Task<IActionResult> ExcelFile(int workRequestId)
        {
            var result = await this.workRequestStateApiService.GetWorkRequestStatesAsync(workRequestId);

            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            ExcelPackage excelPackage = new ExcelPackage();

            var excelModel = result.Data.Select(x => new ExcelPdfModel
            {
                Description = x.Description
            });

            var excelBank = excelPackage.Workbook.Worksheets.Add("Faaliyet Raporu");

            excelBank.Cells["A1"].LoadFromCollection(excelModel,true);

            var bytes = excelPackage.GetAsByteArray();
            return File(bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", Guid.NewGuid() + ".xlsx");
        }

    

        public async Task<IActionResult> PdfFile(int workRequestId)
        {
            DataTable dataTable = new DataTable();

            var result = await this.workRequestStateApiService.GetWorkRequestStatesAsync(workRequestId);

            var pdfModel = result.Data.Select(x => new ExcelPdfModel
            {
                Description = x.Description
            });

            dataTable.Load(ObjectReader.Create(pdfModel));


            string fileName = Guid.NewGuid() + ".pdf";

            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/documents/" + fileName);
            var stream = new FileStream(path, FileMode.Create);



            var document = new iTextSharp.text.Document(PageSize.A4, 25f, 25f, 25f, 25f);

            PdfWriter.GetInstance(document, stream);

            document.Open();


            PdfPTable pdfPTable = new PdfPTable(dataTable.Columns.Count);

            for (int i = 0; i < dataTable.Columns.Count; i++)
            {
                pdfPTable.AddCell(dataTable.Columns[i].ColumnName);
            }


            for (int i = 0; i < dataTable.Rows.Count; i++)
            {
                for (int j = 0; j < dataTable.Columns.Count; j++)
                {
                    pdfPTable.AddCell(dataTable.Rows[i][j].ToString());
                }
            }



            document.Add(pdfPTable);

            document.Close();
            return File("/documents/" + fileName, "application/pdf", fileName);
        }

        public IActionResult Create(int workRequestId)
        {
            return View(new CreateWorkRequestStateModel { WorkRequestId = workRequestId });
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateWorkRequestStateModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await this.workRequestStateApiService.CreateAsync(model);

                return RedirectToAction("Index", new { @workRequestId = model.WorkRequestId });
            }
            return View(model);
        }

        public async Task<IActionResult> Update(int id, int workRequestId)
        {


            var result = await this.workRequestStateApiService.GetAsync(id);
            return View(new UpdateWorkRequestStateModel
            {
                Id = result.Data.Id,
                Description = result.Data.Description,
                WorkRequestId = workRequestId
            });
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateWorkRequestStateModel model)
        {

            if (ModelState.IsValid)
            {
                var result = await this.workRequestStateApiService.UpdateAsync(model);
                return RedirectToAction("Index", new { @workRequestId = model.WorkRequestId }); 
            }


            return View(model);
        }

        public async Task<IActionResult> Delete(int id, int workRequestId)
        {
            await this.workRequestStateApiService.DeleteAsync(id);
            return RedirectToAction("Index", new { @workRequestId = workRequestId });
        }

      
    }
}

UpSchool.HelpDesk.PresentationLayer/Views/WorkRequestState/Create.cshtml
@model CreateWorkRequestStateModel

@{
    Layout = "_Layout";
}

<div class="card">
    <div class="card-body">
        <h3 class="card-title mb-3">Yeni Durum Oluştur</h3>
        <form asp-action="Create" asp-controller="WorkRequestState">
            <input type="hidden" asp-for="WorkRequestId" value="@Model.WorkRequestId" />
        
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Açıklama</label>
                <textarea class="form-control" asp-for="Description" rows="3"></textarea>
            </div>
            <div class="form-group text-danger" asp-validation-summary="All" >


            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg w-100">Kaydet</button>
            </div>
        </form>

    </div>

</div>

UpSchool.HelpDesk.PresentationLayer/Views/WorkRequestState/Index.cshtml
@model List<WorkRequestStateModel>

@{
    Layout = "_Layout";
}

<div class="row">
    <div class="col-12">


        @if (Model?.Count > 0)
        {
            <div class="card mb-4">
                <div class="card-header pb-0">
                    <h6>İş ile kaydedilen durumlar</h6>
                    <a asp-action="Create" asp-controller="WorkRequestState" asp-route-workRequestId="@ViewBag.WorkRequestId" class="btn btn-primary btn-sm">Yeni Durum Oluştur</a>

                    <a asp-action="ExcelFile" asp-controller="WorkRequestState" asp-route-workRequestId="@ViewBag.WorkRequestId" class="btn btn-success btn-sm">Excel</a>

                    <a asp-action="PdfFile" asp-controller="WorkRequestState" asp-route-workRequestId="@ViewBag.WorkRequestId" class="btn btn-danger btn-sm">PDF</a>
                </div>
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center justify-content-center mb-0">
                            <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Description</th>


                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <span class="ps-3 text-xs text-center font-weight-bold ">@item.Description</span>
                                        </td>

                                        <td>
                                            <span class="ps-1 text-xs text-center font-weight-bold">


                                                <a asp-action="Update" asp-controller="WorkRequestState" asp-route-id="@item.Id" asp-route-workRequestId="@ViewBag.WorkRequestId" class="btn btn-warning btn-xs">Güncelle</a>
                                                <a asp-action="Delete" asp-controller="WorkRequestState" asp-route-workRequestId="@ViewBag.WorkRequestId" asp-route-id="@item.Id" class="btn btn-danger btn-xs">Sil</a>


                                            </span>
                                        </td>
                                      


                                    </tr>
                                }


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="card">
                <!-- Card image -->
                <div class="card-header p-0 mx-3 mt-3 position-relative z-index-1">
                </div>
                <!-- Card body -->
                <div class="card-body">
                    <h3 class="card-title mb-3">Uyarı</h3>
                    <p class="card-text mb-4">Herhangi bir veri bulunamadı.</p>
                    <a asp-action="Create" asp-controller="WorkRequestState" asp-route-workRequestId="@ViewBag.WorkRequestId" class="btn btn-primary">Yeni Durum Oluştur</a>
                </div>
            </div>
        }





    </div>
</div>

UpSchool.HelpDesk.PresentationLayer/Views/WorkRequestState/Update.cshtml
@model UpdateWorkRequestStateModel

@{
    Layout = "_Layout";
}

<div class="card">
    <div class="card-body">
        <h3 class="card-title mb-3">Durum Düzenle</h3>
        <form asp-action="Update" asp-controller="WorkRequestState">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="WorkRequestId"/>
           
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Açıklama</label>
                <textarea class="form-control" asp-for="Description" rows="3"></textarea>
            </div>
            <div class="form-group text-danger" asp-validation-summary="All" >


            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg w-100">Kaydet</button>
            </div>
        </form>

    </div>

</div>